name: .NET Core

on:
  push:
    paths: 
      - 'apis/poi/**'
    branches: [ master ]
  pull_request:
    paths: 
      - 'apis/poi/**'
    branches: [ master ]

jobs:
  build:
    name: "build net"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: apis/poi
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: apis/poi
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: apis/poi/tests/UnitTests
    - name: Create Issue Action
      if: failure()
      uses: nashmaniac/create-issue-action@v1.1
      with:
    # Title of the issue
        title: Issue with build 
    # Token of the user that creates the issue
        token: ${{secrets.GITHUB_TOKEN}}
        body: Workflow failed for commit ${{github.sha}}
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    name: "release"
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    
    - uses: azure/docker-login@v1
      with:
        login-server: contoso.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t openhackn82382w0acr.azurecr.io/api-poi:${{ github.run_id }}
        docker push openhackn82382w0acr.azurecr.io/api-poi:${{ github.run_id}} 
      
    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'node-rnc'
        images: 'contoso.azurecr.io/nodejssampleapp:${{ github.run_id }}'
    
    - name: Azure logout
      run: |
        az logout
   
