name: .NET Core
env:
  ACRREGISTRY: openhackn82382w0acr.azurecr.io
  APPNAME:  openhackn82382w0poi
  RGNAME: openhackn82382w0rg
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


on:
  issues:


jobs:
  deploytoprod:
    if: github.event.label.name == 'approved'
    name: "deploy to prod"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
  swap_slots:
    runs-on: ubuntu-latest
    name: "swap slots"
    needs: [deploytoprod]
    steps:    
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - run: az webapp deployment slot swap  -g ${{ env.RGNAME}}  -n ${{ env.APPNAME}}  --slot staging   --target-slot production 
        
  validate_prod_web_app:
    runs-on: ubuntu-latest
    name: "Validate All Working In Prod"
    needs: [swap_slots]
    steps:
      - run: | 
            wget https://raw.githubusercontent.com/ahmedsza/ohdevops/master/pollingprod.sh
            bash pollingprod.sh
       
      - run: echo "There is a problem in prod"
        if:  failure()
      
      - run: echo "All good"
        if : env.APIPRODSTATUS == 'true'
        
  swap_slots_for_bad:
    runs-on: ubuntu-latest
    name: "swap slots for bad deploy"
    needs: [validate_prod_web_app]
    if : failure()
    steps:    
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - run: az webapp deployment slot swap  -g ${{ env.RGNAME}}  -n ${{ env.APPNAME}}  --slot staging   --target-slot production 
    
    
      

