name: simpletes

on:
  push:
    branches: [ master ]

jobs:
  validate_web_app:
    runs-on: ubuntu-latest
    name: "Validate All Working"
    steps:
      - run: | 
            wget https://raw.githubusercontent.com/ahmedsza/ohdevops/master/polling.sh
            bash polling.sh
       
      - run: echo "I have file!"
        if:  failure()
      
      - run: echo "API status true!"
        if:  env.APISTATUS == 'true'
